# Generated by Django 4.2.7 on 2025-11-23 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        ('clients', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('send_to_all', models.BooleanField(default=False, help_text='Send to all active clients')),
                ('only_marketing_subscribers', models.BooleanField(default=True, help_text='Only send to clients who opted in for marketing emails')),
                ('only_active_clients', models.BooleanField(default=True, help_text='Only send to active clients')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='When to send the campaign', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('emails_failed', models.PositiveIntegerField(default=0)),
                ('emails_opened', models.PositiveIntegerField(default=0)),
                ('links_clicked', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_clients', models.ManyToManyField(blank=True, help_text='Specific clients to send to', related_name='email_campaigns', to='clients.client')),
            ],
            options={
                'verbose_name': 'Email Campaign',
                'verbose_name_plural': 'Email Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('REMINDER', 'Appointment Reminder'), ('CONFIRMATION', 'Appointment Confirmation'), ('FOLLOWUP', 'Follow-up Email'), ('MARKETING', 'Marketing Email'), ('NEWSLETTER', 'Newsletter'), ('BIRTHDAY', 'Birthday Greeting'), ('WELCOME', 'Welcome Email'), ('PACKAGE_EXPIRY', 'Package Expiry Warning'), ('REFERRAL', 'Referral Program'), ('CUSTOM', 'Custom Email')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField(help_text='HTML email content. Use {{variable}} for dynamic content.')),
                ('text_content', models.TextField(blank=True, help_text='Plain text version of the email')),
                ('available_variables', models.TextField(blank=True, help_text='Comma-separated list of available variables (e.g., client_name, appointment_date)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('REMINDER', 'Appointment Reminder'), ('FOLLOWUP', 'Follow-up'), ('BIRTHDAY', 'Birthday'), ('PACKAGE_EXPIRY', 'Package Expiry'), ('CUSTOM', 'Custom')], max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('rendered_html', models.TextField(blank=True)),
                ('rendered_text', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_emails', to='appointments.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_emails', to='clients.client')),
                ('package_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_emails', to='packages.packagepurchase')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_emails', to='communications.emailtemplate')),
            ],
            options={
                'verbose_name': 'Scheduled Email',
                'verbose_name_plural': 'Scheduled Emails',
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('sent_to', models.EmailField(max_length=254)),
                ('email_type', models.CharField(max_length=50)),
                ('sent_successfully', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='communications.emailcampaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='clients.client')),
                ('scheduled_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='communications.scheduledemail')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='communications.emailtemplate'),
        ),
        migrations.AddIndex(
            model_name='scheduledemail',
            index=models.Index(fields=['status', 'scheduled_for'], name='communicati_status_d04599_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledemail',
            index=models.Index(fields=['email_type', 'status'], name='communicati_email_t_ce46f3_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['sent_at'], name='communicati_sent_at_6b7b29_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['client', 'email_type'], name='communicati_client__031977_idx'),
        ),
    ]
