# Generated by Django 4.2.7 on 2025-11-23 15:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        ('clients', '0001_initial'),
        ('appointments', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Unique discount code', max_length=50, unique=True)),
                ('description', models.TextField()),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Off'), ('FIXED', 'Fixed Amount Off'), ('FREE_SESSION', 'Free Session(s)'), ('BOGO', 'Buy One Get One')], max_length=20)),
                ('applies_to', models.CharField(choices=[('PACKAGE', 'Package'), ('SERVICE', 'Service'), ('ALL', 'All Purchases')], max_length=20)),
                ('percentage_off', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('fixed_amount_off', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed dollar amount off', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('free_sessions', models.PositiveIntegerField(default=0, help_text='Number of free sessions')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses_total', models.PositiveIntegerField(blank=True, help_text='Maximum total uses (null = unlimited)', null=True)),
                ('max_uses_per_client', models.PositiveIntegerField(default=1, help_text='Maximum uses per client')),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('minimum_purchase_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum purchase amount required', max_digits=10, null=True)),
                ('can_be_combined', models.BooleanField(default=False, help_text='Can this discount be combined with other discounts?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_packages', models.ManyToManyField(blank=True, help_text='Specific packages this discount applies to', related_name='discounts', to='packages.package')),
                ('applicable_services', models.ManyToManyField(blank=True, help_text='Specific services this discount applies to', related_name='discounts', to='services.service')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Amount discounted', max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Original price before discount', max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, help_text='Final price after discount', max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to='appointments.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to='clients.client')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.discount')),
                ('package_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to='packages.packagepurchase')),
            ],
            options={
                'verbose_name': 'Discount Usage',
                'verbose_name_plural': 'Discount Usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REWARDED', 'Rewarded')], default='PENDING', max_length=20)),
                ('referral_date', models.DateField(auto_now_add=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('rewarded_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('referred_client', models.ForeignKey(help_text='Client who was referred', on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to='clients.client')),
                ('referred_discount', models.ForeignKey(blank=True, help_text='Discount given to referred client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_rewards', to='discounts.discount')),
                ('referrer', models.ForeignKey(help_text='Client who made the referral', on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='clients.client')),
                ('referrer_discount', models.ForeignKey(blank=True, help_text='Discount given to referrer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrer_rewards', to='discounts.discount')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-referral_date'],
                'unique_together': {('referrer', 'referred_client')},
            },
        ),
    ]
