# Generated by Django 4.2.7 on 2025-11-23 15:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ENERGY', 'Fatigue / Focus / Energy'), ('PAIN', 'Pain and Inflammation'), ('INJURY', 'Injury Recovery and Prevention'), ('BEAUTY', 'Beauty and Skin Health'), ('WELLNESS', 'Wellbeing and Stress Relief'), ('CUSTOM', 'Custom Package')], max_length=20)),
                ('description', models.TextField()),
                ('total_sessions', models.PositiveIntegerField(help_text='Total number of sessions in the package', validators=[django.core.validators.MinValueValidator(1)])),
                ('min_sessions_per_week', models.PositiveIntegerField(blank=True, help_text='Minimum sessions per week recommended', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_sessions_per_week', models.PositiveIntegerField(blank=True, help_text='Maximum sessions per week recommended', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Total package price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('validity_days', models.PositiveIntegerField(default=90, help_text='Number of days the package is valid from purchase')),
                ('can_combine_services', models.BooleanField(default=False, help_text='Can multiple services be used in the same visit?')),
                ('is_active', models.BooleanField(default=True)),
                ('benefits', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services', models.ManyToManyField(help_text='Services included in this package', related_name='packages', to='services.service')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackagePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Original package price', max_digits=10)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount amount', max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, help_text='Final price paid', max_digits=10)),
                ('total_sessions', models.PositiveIntegerField()),
                ('sessions_used', models.PositiveIntegerField(default=0)),
                ('sessions_remaining', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_purchases', to='clients.client')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='packages.package')),
            ],
            options={
                'verbose_name': 'Package Purchase',
                'verbose_name_plural': 'Package Purchases',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
